// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx5ZLCBfybbYThdyxA9YUTar89LvDgnK8',
    appId: '1:254561259467:web:74190847776448074bf04e',
    messagingSenderId: '254561259467',
    projectId: 'medicine-1c8af',
    authDomain: 'medicine-1c8af.firebaseapp.com',
    storageBucket: 'medicine-1c8af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4d9T7zujB19jXDQ1I7PyFPBYnkFJN2U',
    appId: '1:254561259467:android:52f56861aaf167fe4bf04e',
    messagingSenderId: '254561259467',
    projectId: 'medicine-1c8af',
    storageBucket: 'medicine-1c8af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcn4mlAcr3bmti_Z37TH4FfRjVDnbfzAo',
    appId: '1:254561259467:ios:72092edf71ff93934bf04e',
    messagingSenderId: '254561259467',
    projectId: 'medicine-1c8af',
    storageBucket: 'medicine-1c8af.firebasestorage.app',
    iosBundleId: 'com.example.mediscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcn4mlAcr3bmti_Z37TH4FfRjVDnbfzAo',
    appId: '1:254561259467:ios:72092edf71ff93934bf04e',
    messagingSenderId: '254561259467',
    projectId: 'medicine-1c8af',
    storageBucket: 'medicine-1c8af.firebasestorage.app',
    iosBundleId: 'com.example.mediscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx5ZLCBfybbYThdyxA9YUTar89LvDgnK8',
    appId: '1:254561259467:web:bd6201dbb147d61a4bf04e',
    messagingSenderId: '254561259467',
    projectId: 'medicine-1c8af',
    authDomain: 'medicine-1c8af.firebaseapp.com',
    storageBucket: 'medicine-1c8af.firebasestorage.app',
  );

}